server:
  port: 8080
  
spring:
  autoconfigure:
    exclude:
      - org.springframework.cloud.aws.autoconfigure.context.ContextStackAutoConfiguration
  metrics:
    export:
      statsd:
        prefix: local
        host: localhost
  redis:
    host: localhost
    port: 6379
      
aws:
  # Collector schedule (required)
  ## once every 5 minutes
  cron: 0 0/5 * * * *

  # AWS ValidTag Key - To look for tags that you expect on your resource
  validTagKey:
    - Name
    - Application
    - Environment
    - Stack
    - Role
    - Owner

  # AWS Proxy Host
  proxyHost: localhost

  # AWS Proxy Port
  proxyPort: 3333

  # AWS Non Proxy
  nonProxy: 169.254.169.254

  # AWS Profile to be used if any
  profile: default
  
logbook:
  exclude:
    - /favicon.ico
    - /health
    - /prometheus
    - /v2/api-docs
  filter.enabled: true
  format.style: json
  obfuscate:
    headers:
      - Authorization
      - X-Secret
    parameters:
      - access_token
      - password
  write:
    category: http.wire-log
    level: INFO
